apiVersion: v1
kind: Service
metadata:
  name: aksappdemo
  namespace: aksappdemo
  labels:
    app.kubernetes.io/name: aksappdemo
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aksappdemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000